### ISSUE TITLE
Incorrect TAB region for interface{}

### ISSUE THREAD

**Issue by seagle0128** [tigersoldier/company-lsp#55] opened 2018-09-12 08:07 UTC
Hi, I am enjoying lsp-mode and company-lsp mostly. Just one minor issue as the screencast below. In `(..., interface{})`, press `TAB`, the `)` will be deleted incorrectly. I am using Emacs 26 with the latest `company-lsp` on Ubuntu LTS 18.04. This issue exists on all OS platforms.

![company-lsp](https://user-images.githubusercontent.com/140797/45410791-37fd3400-b6a5-11e8-81b9-1380df98feba.gif)

**Comment by tigersoldier** [comment] 2018-09-15 01:30
Hi can you clarify? In the screencast I saw the closing`)` disappeared when you type `"`, not tab.

Does it only happen when completing for parameters of type `interface{}`, or any type?

**Comment by seagle0128** [comment] 2018-09-16 14:34
`interfaces{}` is included. I attched the output below.

[company-diag.txt](https://github.com/tigersoldier/company-lsp/files/2386651/company-diag.txt)

**Comment by tigersoldier** [comment] 2018-09-17 20:06
The snippet sent from Go language server doesn't escape `{`. The snippet is like `panic(${1:interface{\\}})$0`, which can't be handled by yasnippet. Changing that to `panic(${1:interface\\{\\}})$0` works fine.

I'll do some test with my language server to see if escaping `\\{` works in VS code. If yes, it makes sense for Go language server to escape it. If not, I'll escape it in company-lsp

**Comment by tigersoldier** [comment] 2018-09-17 22:47
OK, VS code doesn't treat escaped `{` specially. Fixed by dd7610ac0083faa769b43c7f84f966c5316082a6

**Closed** 2018-09-17 22:47 UTC

**Comment by seagle0128** [comment] 2018-09-18 03:02
It does work well. Thanks very much, @tigersoldier !

**Comment by edkolev** [comment] 2018-11-26 13:35
The above issue might be caused by go's language server.

I tested this with eglot was well, and this is a message I saw in eglot's log (sorry, I'm not sure how to get such a log using lsp-mode) - the `:newText` seems messed up:

```
(:label "Run" :kind 3 :detail "func(name string, f func(t *testing.T)) bool" :insertText "Run(${1:name string}, ${2:f func(t *testing.T})$0" :insertTextFormat 2 :textEdit
                             (:range
                              (:start
                               (:line 9 :character 3)
                               :end
                               (:line 9 :character 3))
                              :newText "Run(${1:name string}, ${2:f func(t *testing.T})$0"))
```
